#!/usr/bin/env python


import unittest

import jsonrpc.tests.test_jsonutil
import jsonrpc.tests.test_proxy
import jsonrpc.tests.test_server


loader = unittest.TestLoader()

suite = loader.loadTestsFromModule(jsonrpc.tests.test_jsonutil)
suite.addTests(loader.loadTestsFromModule(jsonrpc.tests.test_proxy))
suite.addTests(loader.loadTestsFromModule(jsonrpc.tests.test_server))

runner = unittest.TextTestRunner(verbosity=2)
runner.run(suite)

